### ISSUE TITLE
Invalid JSON returned

### ISSUE THREAD

**Issue by BertilJ** [filcole/pycarwings2#12]
I've started to see this quite regularly in my log. Don't know what it is about yet, but I'll see if I can find that.

> 2019-02-01 06:02:05 ERROR (SyncWorker_1) [pycarwings2.pycarwings2] Invalid JSON returned

**Comment by filcole** [comment]
I was seeing the Nissan servers returning HTML error pages instead of JSON, so put in a check to see if valid JSON was being returned.  If not, then the above error message was returned.

**Comment by BertilJ** [comment]
Ok, closing.
