### ISSUE TITLE
Where To Collaborate and Discus the API?

### ISSUE THREAD

**Issue by ds17f** [filcole/pycarwings2#17]
Hey there,

Love your work and thank you for keeping all of this current and functional.  I'm working on a javascript library (mostly Node) so that I can build an Nissan Leaf app for my FitBit.  I'm curious if there is a good source of information on the API.  So far I've just used your project for reference and I've bounced around on some of the comments and links you've got here.

Any idea where we can collaborate?  Any interest in getting a slack group started? 

(sorry to open this as an issue, I'm not sure how else to reach out to you.)

**Comment by filcole** [comment]
Best place I believe is here or the source for the MyLeaf app I think: https://gitlab.com/tobiaswkjeldsen/carwingsflutter
