### ISSUE TITLE
JSON error since 2021-09-13

### ISSUE THREAD

**Issue by pnlrogue1** [filcole/pycarwings2#31]
Script ran fine on 12th September at 10pm (UK time) but hasn't run since. On manually running, I'm seeing a JSON error:

```
Prepare Session
Login...
Invalid JSON returned
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pycarwings2/pycarwings2.py", line 158, in _request
    j = json.loads(response.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/leafapp/get-leaf-info.py", line 115, in <module>
    leaf = s.get_leaf()
  File "/home/pi/.local/lib/python3.7/site-packages/pycarwings2/pycarwings2.py", line 217, in get_leaf
    self.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/pycarwings2/pycarwings2.py", line 179, in connect
    "lg": "en-US",
  File "/home/pi/.local/lib/python3.7/site-packages/pycarwings2/pycarwings2.py", line 161, in _request
    raise CarwingsError
pycarwings2.pycarwings2.CarwingsError
```

I'm on Pycarwings2 2.11. I see you pushed a new version (2.12) but that doesn't seem to have made it into PyPI - do I just need to wait until it's there and do an upgrade?

**Comment by bskan** [comment]
I've come across the same problem myself, I'm on 2.11 because I installed using pip. 

I think it's just line 75 of the pycarwings2.py that's changed because it looks like they've now retired the old API URL

BASE_URL = "https://gdcportalgw.its-mo.com/api_v210707_NE/gdc/"

**Comment by pnlrogue1** [comment]
Yep - updating that solved it. @filcole do we have an idea when 2.12 will hit PyPI so others can get the fix? I'm not a huge fan of having a local copy of the module with drift from the master...

**Comment by bangan1910** [comment]
I have needed to edit manually the last few updates. Will the new api url be updated in the newer updates or should i try to automate the editing?

**Comment by kevin7s-io** [comment]
FWIW, I pulled the latest from pip and updated the URL on ::75 and I'm receiving the same error.

```
DEBUG:pycarwings2.pycarwings2:Response HTTP Status Code: 200
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: b'{"status":"-2010","message":"INVALID PARAMS"}'
ERROR:pycarwings2.pycarwings2:carwings error INVALID PARAMS: -2010
```

I've, obviously, validated my credentials are fine through the web/app. I'm in the "NNA" region.

**Comment by bwduncan** [comment]
@filcole Any chance you could have a look at this and push a release to PyPI? Hoping that will get picked up in the next home assistant release and close another issue.

**Comment by engelchrisi** [comment]
@filcole : what about adding an optional parameter to the constructor for the BASE_URL and then on home assistant side allow an optional configuration of the BASE_URL. This will prevent the home assistant leaf integration to fail the next month until the hard coded BASE_URL within your pycarwings2 lib reaches the home assistant milestone.

nissan_leaf:
  username: "YOUR_USERNAME"
  password: "YOUR_PASSWORD"
  region: "YOUR_REGION"
  base_url: "https://gdcportalgw.its-mo.com/api_v220xyz_NE"

**Comment by filcole** [comment]
@bwduncan Version 2.12 is now on pip.  Now to update HA to use version 2.12.  

@engelchrisi the problem is it's not just the URL that keeps changing, it's the referrer too.  HA tries to isolate itself from these issues via using pip modules.
