### ISSUE TITLE
"BatteryStatusRecords":[]

### ISSUE THREAD

**Issue by hansnull** [filcole/pycarwings2#38]
Hi Guys,

the Nissan API always returns an empty array for the BatteryStatusRecords:
`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gdcportalgw.its-mo.com:443
DEBUG:urllib3.connectionpool:https://gdcportalgw.its-mo.com:443 "POST /api_v210707_NE/gdc/BatteryStatusRecordsRequest.php HTTP/1.1" 200 None
DEBUG:pycarwings2.pycarwings2:Response HTTP Status Code: 200
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: b'{"status":200,"BatteryStatusRecords":[]}'`

Has anybody an idea why this is happening?

Any help appreciated
hansnull

**Comment by filcole** [comment]
Hi @hansnull, Difficult to know why it's not working for you.  I'm getting responses from `BatteryStatusRecordsRequest.php` with a populated `BatteryStatusRecords`

**Comment by hansnull** [comment]
Thanks for your reply, seems to be related to my car then : (
