### ISSUE TITLE
pycarwings2 - v2.13 - INVALID PARAMS

### ISSUE THREAD

**Issue by Heiner3** [filcole/pycarwings2#39]
Hi everybody, 
after searching endless hours the web, I hope somebody can help me here. 
I installed pycarwings2 v2.13 on my Raspberry Pi together with solaranzeige.de and smartWB. 
Both are running flawless but I would like to incorporate the batteries SOC to prevent overloading my Nissan Leafs battery. Unfortunately it doesn't work for me. When I run **get-leaf-info.py** the result is:

```
DEBUG:root:login = "removed for privacy reasons", password = "removed for privacy reasons", region = NE
Prepare Session
Login...
DEBUG:pycarwings2.pycarwings2:invoking carwings API: https://gdcportalgw.its-mo.com/api_v210707_NE/gdc/InitialApp_v2.php
DEBUG:pycarwings2.pycarwings2:params: {
   "RegionCode": "NE",
   "custom_sessionid": "",
   "initial_app_str": "9s5rfKVuMrT03RtzajWNcA",
   "lg": "en-US"
}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gdcportalgw.its-mo.com:443
DEBUG:urllib3.connectionpool:https://gdcportalgw.its-mo.com:443 "POST /api_v210707_NE/gdc/InitialApp_v2.php HTTP/1.1" 200 None
DEBUG:pycarwings2.pycarwings2:Response HTTP Status Code: 200
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: b'{"status":200,"message":"success","baseprm":"88dSp7wWnV3bvv9Z88zEwg"}'
DEBUG:pycarwings2.pycarwings2:invoking carwings API: https://gdcportalgw.its-mo.com/api_v210707_NE/gdc/UserLoginRequest.php
DEBUG:pycarwings2.pycarwings2:params: {
   "Password": "sL91eykAuzzU28gB8YJwVg==",
   "RegionCode": "NE",
   "UserId": "removed for privacy reasons",
   "custom_sessionid": "",
   "initial_app_str": "9s5rfKVuMrT03RtzajWNcA"
}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gdcportalgw.its-mo.com:443
DEBUG:urllib3.connectionpool:https://gdcportalgw.its-mo.com:443 "POST /api_v210707_NE/gdc/UserLoginRequest.php HTTP/1.1" 200 None
DEBUG:pycarwings2.pycarwings2:Response HTTP Status Code: 200
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: b'{"status":"AAS-605","message":"INVALID PARAMS"}'
ERROR:pycarwings2.pycarwings2:carwings error INVALID PARAMS: AAS-605
Traceback (most recent call last):
  File "get-leaf-info.py", line 61, in <module>
    leaf = s.get_leaf()
  File "/home/pi/.local/lib/python3.7/site-packages/pycarwings2/pycarwings2.py", line 219, in get_leaf
    self.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/pycarwings2/pycarwings2.py", line 193, in connect
    "Password": encodedPassword,
  File "/home/pi/.local/lib/python3.7/site-packages/pycarwings2/pycarwings2.py", line 167, in _request
    raise CarwingsError("INVALID PARAMS")
pycarwings2.pycarwings2.CarwingsError: INVALID PARAMS
------------------
(program exited with code: 1)
Press return to continue
```

Can somebody help me here?

**Comment by Heiner3** [comment]
By the way: The android-apps **NissanConnect** and **My Leaf** are running well here (in Germany)...

**Comment by Ez2517-Git** [comment]
Really strange ... for me, pycarwings2 still works (located in Austria). I just double checked and my pycarwings2 version is almost identical to the version 2.13 from here. URL is the same, still no "User-Agent" in the headers,.....

**Comment by Ez2517-Git** [comment]
Btw, I had strange issues in the past when I used special characters in my Carwings password. Shouldn't be the issue here since it apparently worked before, but it might still be worth a try to change back to a simple password in case you currently are using special characters too ...

**Comment by Heiner3** [comment]
> Btw, I had strange issues in the past when I used special characters in my Carwings password. Shouldn't be the issue here since it apparently worked before, but it might still be worth a try to change back to a simple password in case you currently are using special characters too ...

**Comment by Heiner3** [comment]
@[Ez2517-Git Thanks for the hint. Something like that I had before anywhere too. 
So I changed the password - but it's still the same. 
I also remember when they updated the NissanConnect Services App, I had a "+" in the PW and this was not allowed anymore. Then I changed the "+" into "%" and it happend a miracle: It continued to run with the old special character "+" 
Unfortunately the PW needs to incorporate one of the special characters "!?@£$*#+="
My app NissanConnect now runs with the "!".....

**Comment by Ez2517-Git** [comment]
I just tried to add a '!' to my PW to find out whether that causes issues with pycarwings2. However there is a problem, when I try to change the PW on the You+Nissan Website (I added an ! at the end of my 9 digit PW), the website behaves as if the change was succesful (at least there is no error message), but when I log out and try to log in again, the PW in fact did not change...

Btw, on the You+Nissan site in the area where you can change your PW it says: 'Machen Sie Ihr Passwort sicherer, indem Sie acht alphanumerische Zeichen verwenden (ohne Sonderzeichen).'

So I get the feeling that your issue could indeed be PW related ...

**Comment by Heiner3** [comment]
@Ez2517-Git – Thanks again! I think you might be right. But how establish a PW without special characters? 
In the **NissanConnect** Services App a special character is a must (see above) and a registration at **you+nissan** is not possible for me. (information by [germany@nissan-services.eu]: my Nissan Leaf is to new (2021) and therefore not compatible with you+nissan)

At the app **My Leaf** > login screen: I realized that the region code was set to _World_, and indeed _Europe_ doesn’t work. 
Here at Help is written: “If you have a vehicle that was produced after May 2019 you need to select ‘World’ as you region”

Then I explored the "**My Leaf**" App’s source code dartcarwings > carwings_session.dart.  _World_ was not declared there: 
Line
 ```
9	enum CarwingsRegion { World, USA, Europe, Canada, Australia, Japan }
 |
182	 String _getRegionName(CarwingsRegion region) {
183		switch (region) {
184		  case CarwingsRegion.USA:
185			return 'NNA';
186		  case CarwingsRegion.Europe:
187			return 'NE';
188		  case CarwingsRegion.Canada:
189			return 'NCI';
190		  case CarwingsRegion.Australia:
191			return 'NMA';
192		  case CarwingsRegion.Japan:
193			return 'NML';
194		  default:
195			return 'NE'; 
196		}
197	}

```
The default = 'NE' I had all the time and other RegionCodes also didn’t work. 
Then I activated the debug mode in My Leaf and in the log Region is not to find at all!
**My suspicion is now: 
pycarwings2 v2.13 (from Dec 26, 2021) is unable to collaborate with Leafs produced after May 2019**

**Comment by Ez2517-Git** [comment]
Hi,
I think the suspicion is correct - afaik the newer leafs from 05/2019 on use a newer API instead of carwings. Old and new Leafs do use different Nissan apps as well. Some of the third party apps like My Leaf have implemented both interfaces. So you'll need to find a library for the newer interface then ...

**Comment by Ez2517-Git** [comment]
Have a look here:

https://tobis.dk/blog/my-leaf-new-apis/

**Comment by Ez2517-Git** [comment]
Or here ))

https://openwb.de/forum/viewtopic.php?t=432&start=30

**Comment by Heiner3** [comment]
It's really true: pycarwings2 v2.13 (**_from Dec 26, 2021_**) runs only with Leafs produced **_before May 2019_**!
In the meanwhile I installed **dartnissanconnect** which runs well **_sometimes only_**. 
I continue despair!

**Comment by filcole** [comment]
Yes, pycarwings2 only supports older nissan leafs.  Tobias does a great job with myleaf.
