### ISSUE TITLE
pip3 install not including ./examples

### ISSUE THREAD

**Issue by arvidrosenhave** [filcole/pycarwings2#41]
I'm a bit new to this, so it might just be user error. But after following the install procedure described in the readme (pip3 install pycarwings2), the ./examples folder is nowhere to be found on my system. How do I get hold of the example files and configuration?

**Comment by filcole** [comment]
I would clone from github.  e.g. https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
